spring:
  profiles:
    include: datasource
---
server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka
    register-with-eureka: true
  instance:
    instance-id: service-additional1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  profiles: service-additional1
  application:
    name: service-additional
---
server:
  port: 8782
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka
    register-with-eureka: true
  instance:
    instance-id: service-additional2
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  profiles: service-additional2
  application:
    name: service-additional