
custom:
  account:
    first-error-account-lock-time: 3
    first-error-account-error-count: 5
    second-error-account-lock-time: 30
    second-error-account-error-count: 10
    third-error-account-lock-time: 3
    third-error-account-error-count: 15
  verification-code:
    code-len: 6 #验证码长度
    code-expires: 10 #验证码失效时间  单位：分钟
    code-requesting-party-lock-time: 24 #验证码请求方锁定时间 单位:小时
    code-requesting-party-max-count: 100 #同一个请求最大的验证码数量
  jwt:
    header: authorization
    expiration: 2
    refresh-expiration: 6
    remember-me-expiration: 30
    remember-me-refresh-expiration: 40
    token-head: Bearer
    secret: 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
spring:
  profiles:
    include: redis,datasource
