---
server:
  port: 8771
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka
    register-with-eureka: true
  instance:
    instance-id: service-user1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  profiles: service-user1
  application:
    name: service-user
---
server:
  port: 8772
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server1:8761/eureka,http://admin:admin@eureka-server2:8762/eureka
    register-with-eureka: true
  instance:
    instance-id: service-user2
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
spring:
  profiles: service-user2
  application:
    name: service-user